### ISSUE TITLE
Alphapose模型转换问题

### ISSUE THREAD

**Issue by TRQ-UP** [soloIife/AlphaPoseOnnx#1]
1.将模型转换后，运行onnx_inference.py文件，输入的图像需要是250*400的尺寸，否者无法后期绘制图像。
2.您是将fast-pose模型直接转换的？没有用到yolov3-spp做检测，是吗？Alphapose原始的pytorch模型是duc_se.pth

**Comment by soloist-v** [comment]
是的，我测试的是这个模型
https://drive.google.com/file/d/1kQhnMRURFiy7NsdS8EFL-8vtqEXOgECn/view
