### ISSUE TITLE
rknn模型预测不正确；

### ISSUE THREAD

**Issue by fjczxl1314** [soloIife/AlphaPoseOnnx#3]
在x86上运行rknn时结果正确，使用rk1808运行时结果错误，api和DRV版本不匹配会导致关键点预测错误吗？

**Comment by fjczxl1314** [comment]
这是转rknn时的日志：
options:
	 Namespace(batch_size=1, dataset='./dataset.txt', onnx='fast_res50_256x192.onnx', platform='rk1808', rknn='./fast_res50_256x192.rknn')
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
--> config model
--> Loading model
onnx model path: fast_res50_256x192.onnx
W Call onnx.optimizer.optimize fail, skip optimize
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/rknn/api/rknn.py:118: RuntimeWarning: overflow encountered in exp
  ret = self.rknn_base.load_onnx(model)
W:tensorflow:From /home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/rknn/api/rknn.py:118: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W:tensorflow:From /home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/rknn/api/rknn.py:118: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W:tensorflow:From /home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/rknn/api/rknn.py:118: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W Unhandle status: the input shape of reshape layer Reshape_Reshape_14_145 is not 4-D
W Unhandle status: the input shape of reshape layer Reshape_Reshape_44_123 is not 4-D
W Unhandle status: the input shape of reshape layer Reshape_Reshape_81_82 is not 4-D
W Unhandle status: the input shape of reshape layer Reshape_Reshape_132_34 is not 4-D
W Do not support shape > 4.
W Unhandle status: the input shape of reshape layer Reshape_Reshape_155_12 is not 4-D
W Do not support shape > 4.
W Unhandle status: the input shape of reshape layer Reshape_Reshape_162_7 is not 4-D
W Do not support shape > 4.
W Unhandle status: the input shape of reshape layer Reshape_Reshape_169_2 is not 4-D
--> Building model
W Do not support shape > 4.
W Do not support shape > 4.
W Do not support shape > 4.
--> Export RKNN model
rknn export success, saved as ./fast_res50_256x192.rknn
done

**Comment by fjczxl1314** [comment]
这是rknn推理时的日志：
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ps/anaconda3/envs/yolo-rknn/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
*************************
all device(s) with ntb mode:
TM018083200400494
*************************
-->loading model : fast_res50_256x192.rknn
--> Init runtime environment on: 
I NPUTransfer: Starting NPU Transfer Client, Transfer version 2.1.0 (b5861e7@2020-11-23T11:50:36)
D RKNNAPI: ==============================================
D RKNNAPI: RKNN VERSION:
D RKNNAPI:   API: 1.6.0 (79320de build: 2020-12-29 10:56:36)
D RKNNAPI:   DRV: 1.3.2 (f113d64 build: 2020-04-23 09:35:26)
D RKNNAPI: ==============================================
done
inps shape:>> (3, 256, 192) float32
(64, 48) 200 26.90625
(64, 48) 88 21.890625
(64, 48) 200 12.328125
(64, 48) 200 50.96875
(64, 48) 200 50.25
(64, 48) 192 27.34375
(64, 48) 2265 27.9375
(64, 48) 200 55.65625
(64, 48) 200 35.46875
(64, 48) 216 30.890625
(64, 48) 200 73.125
(64, 48) 2787 8.609375
(64, 48) 2359 9.2734375
(64, 48) 244 34.25
(64, 48) 200 82.375
(64, 48) 2742 42.15625
(64, 48) 2742 34.375
time: 0.5868346691131592
heat_map_shape: (1, 17, 64, 48)
{'img': '0.jpg', 'result': [{'keypoints': tensor([[ -0.9434,   2.8379],
        [149.1250, -12.5234],
        [ -0.9434,   2.8379],
        [ -3.3066,   2.8379],
        [ -0.9434,   2.8379],
        [-39.9375,   1.6562],
        [  3.7832, 203.7168],
        [ -0.9434,   0.4746],
        [ -0.9434,   2.8379],
        [ 74.6816,   2.8379],
        [ -3.3066,   0.4746],
        [-24.5762, 255.7090],
        [ -8.0332, 213.1699],
        [-19.8496,   5.2012],
        [ -0.9434,   0.4746],
        [-10.3965, 253.3457],
        [-10.3965, 253.3457]]), 'kp_score': tensor([[26.9062],
        [21.8906],
        [12.3281],
        [50.9688],
        [50.2500],
        [27.3438],
        [27.9375],
        [55.6562],
        [35.4688],
        [30.8906],
        [73.1250],
        [ 8.6094],
        [ 9.2734],
        [34.2500],
        [82.3750],
        [42.1562],
        [34.3750]]), 'proposal_score': tensor([140.6631]), 'idx': 0.0, 'bbox': [40.0, 13.0, 67.0, 242.0], 'index': 0}]}
(0, (0, 2))
(1, (149, -12))
(2, (0, 2))
(3, (-3, 2))
(4, (0, 2))
(5, (-39, 1))
(6, (3, 203))
(7, (0, 0))
(8, (0, 2))
(9, (74, 2))
(10, (-3, 0))
(11, (-24, 255))
(12, (-8, 213))
(13, (-19, 5))
(14, (0, 0))
(15, (-10, 253))
(16, (-10, 253))
(17, (-18, 102))

**Comment by soloist-v** [comment]
转换时请注意：
1. 输入和onnx保持一致，具体查看rknn文档
2. rknntoolkit版本 >=1.7
3. 驱动版本 >= 1.7
4. 关闭量化
5. opset<=10

**Comment by soloist-v** [comment]
我是在3399pro测试的

**Comment by fjczxl1314** [comment]
> 我是在3399pro测试的

好的，谢谢！

**Comment by cndcnd085** [comment]
opset<=10  在哪设置

**Comment by soloist-v** [comment]
pytorch

**Comment by cndcnd085** [comment]
我自己按照你的代码复现出来结果了，结果是正确的，可惜的是由于没有量化，每找到一个人的骨骼，就需要1秒中，我使用的是1808的加速卡作的。而且代码中没有人形的detector，估计加上找人，时间会更长。没有量化，实际上rk3399，没有作任何加速完全用cpu跑

**Comment by cndcnd085** [comment]
我自己按照你的代码复现出来结果了，结果是正确的，可惜的是由于没有量化，每找到一个人的骨骼，就需要1秒中，我使用的是1808的加速卡作的。而且代码中没有人形的detector，估计加上找人，时间会更长。没有量化，实际上rk3399，没有作任何加速完全用cpu跑
